# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 12:28
from __future__ import unicode_literals

import colegend.core.fields
import colegend.core.models
import colegend.journals.weekentries.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('journals', '0003_journal_content_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(default=colegend.journals.weekentries.utils.get_current_year, validators=[django.core.validators.MaxValueValidator(4000)])),
                ('week', models.PositiveIntegerField(default=colegend.journals.weekentries.utils.get_current_week, validators=[django.core.validators.MaxValueValidator(54)])),
                ('locations', models.CharField(help_text="Separated by ';'", max_length=255)),
                ('keywords', models.CharField(blank=True, help_text='What were the most important experiences/topics on this week?', max_length=255)),
                ('content', colegend.core.fields.MarkdownField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekentries', to='journals.Journal')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
            options={
                'verbose_name_plural': 'Weekentries',
                'ordering': ['-year', '-week'],
                'verbose_name': 'Week Entry',
            },
            bases=(colegend.core.models.AutoUrlsMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='weekentry',
            unique_together=set([('journal', 'year', 'week')]),
        ),
    ]
