# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekentries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekentry',
            name='locations',
        ),
    ]
