# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekentries', '0002_remove_weekentry_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekentry',
            name='keywords',
            field=models.CharField(blank=True, help_text='What were the most important experiences/topics this week?', max_length=255),
        ),
    ]
