# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:56
from __future__ import unicode_literals

import colegend.core.fields
import colegend.core.models
import colegend.journals.monthentries.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('journals', '0003_journal_content_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(default=colegend.journals.monthentries.utils.get_current_year, validators=[django.core.validators.MaxValueValidator(4000)])),
                ('month', models.PositiveIntegerField(default=colegend.journals.monthentries.utils.get_current_month, validators=[django.core.validators.MaxValueValidator(12)])),
                ('keywords', models.CharField(blank=True, help_text='What were the most important experiences/topics this month?', max_length=255)),
                ('content', colegend.core.fields.MarkdownField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthentries', to='journals.Journal')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
            options={
                'verbose_name_plural': 'Monthentries',
                'verbose_name': 'Month Entry',
                'ordering': ['-year', '-month'],
            },
            bases=(colegend.core.models.AutoUrlsMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='monthentry',
            unique_together=set([('journal', 'year', 'month')]),
        ),
    ]
