# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 19:30
from __future__ import unicode_literals

import colegend.cms.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_joinpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinpage',
            options={'verbose_name': 'Join'},
        ),
        migrations.AddField(
            model_name='joinpage',
            name='content',
            field=wagtail.core.fields.StreamField((('heading', colegend.cms.blocks.HeadingBlock()), ('rich_text', colegend.cms.blocks.RichTextBlock()), ('image', colegend.cms.blocks.ImageBlock()), ('embed', colegend.cms.blocks.EmbedBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())), blank=True),
        ),
    ]
