# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 14:38
from __future__ import unicode_literals

import colegend.core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_habitspage_statspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('area_1', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='area 1')),
                ('area_2', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='area 2')),
                ('area_3', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='area 3')),
                ('area_4', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='area 4')),
                ('area_5', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='area 5')),
                ('area_6', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='area 6')),
                ('area_7', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='area 7')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'scan',
                'verbose_name_plural': 'scans',
                'default_related_name': 'scans',
                'get_latest_by': 'date',
            },
            bases=(colegend.core.models.OwnedCheckMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='scan',
            unique_together=set([('owner', 'date')]),
        ),
    ]
