# Generated by Django 2.0.3 on 2018-04-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180422_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitreminder',
            name='time',
            field=models.DateTimeField(verbose_name='time'),
        ),
    ]
