# Generated by Django 2.0.3 on 2018-04-22 16:33

import colegend.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180422_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='content',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='icon',
            field=models.CharField(blank=True, max_length=255, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='habitreminder',
            name='time',
            field=models.TimeField(verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='content',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='content'),
        ),
    ]
