# Generated by Django 2.0.3 on 2018-04-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180422_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitreminder',
            name='owner',
        ),
    ]
