# Generated by Django 2.0.3 on 2018-04-24 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180423_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='habit',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routinehabit',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_habits', to='home.Habit'),
        ),
        migrations.AlterField(
            model_name='routinehabit',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_habits', to='home.Routine'),
        ),
    ]
