# Generated by Django 2.0.3 on 2018-04-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180424_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_controlled',
            field=models.BooleanField(default=False, help_text='Designates whether this habit is controlled by the system.', verbose_name='controlled'),
        ),
    ]
