# Generated by Django 2.0.3 on 2018-04-24 22:10

import colegend.core.intuitive_duration.modelfields
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180424_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=colegend.core.intuitive_duration.modelfields.IntuitiveDurationField(default=datetime.timedelta(0, 600), verbose_name='duration'),
        ),
    ]
