# Generated by Django 2.0.4 on 2018-04-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180425_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='streak',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='streak'),
        ),
        migrations.AddField(
            model_name='habit',
            name='streak_max',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='best streak'),
        ),
    ]
