# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 11:43
from __future__ import unicode_literals

import colegend.core.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('video_url', models.URLField(blank=True, verbose_name='video url')),
                ('content', colegend.core.fields.MarkdownField()),
            ],
            options={
                'default_related_name': 'tutorials',
                'ordering': ['name'],
            },
        ),
    ]
