# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 09:16
from __future__ import unicode_literals

import annoying.fields
import colegend.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0005_auto_20160123_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('owner',
                 annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                   serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Journals',
                'verbose_name': 'Journal',
            },
            bases=(colegend.core.models.AutoUrlsMixin, models.Model),
        ),
    ]
