# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='spellchecker',
            field=models.BooleanField(default=False),
        ),
    ]
