# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 15:56
from __future__ import unicode_literals

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_journal_spellchecker'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='content_template',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
    ]
