# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:10
from __future__ import unicode_literals

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_journal_content_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='day_content_template',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='month_content_template',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='week_content_template',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
    ]
