# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_auto_20161202_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='day_content_template',
            new_name='day_template',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='month_content_template',
            new_name='month_template',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='week_content_template',
            new_name='week_template',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='content_template',
        ),
    ]
