# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 22:13
from __future__ import unicode_literals

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_auto_20161202_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='day_template',
            field=colegend.core.fields.MarkdownField(default="# Morning\nDream notes: \n\nThis morning I am grateful for:\n\n1. \n2. \n3. \n\nMy Legend Purpose: \n\nToday's focus outcomes:\n\n1. \n2. \n3. \n\n# Day\n??:00 I woke up.\n\n# Evening\nLessons learned: \n\nWins: \n\nTonight I am grateful for:\n\n1. \n2. \n3. \n"),
        ),
        migrations.AlterField(
            model_name='journal',
            name='month_template',
            field=colegend.core.fields.MarkdownField(default="# Month\nMonths's focus outcomes:\n\n1. \n2. \n3. \n\nLessons learned: \n\nWins: \n\nThis month am grateful for:\n\n1. \n2. \n3. \n"),
        ),
        migrations.AlterField(
            model_name='journal',
            name='week_template',
            field=colegend.core.fields.MarkdownField(default="# Week\nWeeks's focus outcomes:\n\n1. \n2. \n3. \n\nLessons learned: \n\nWins: \n\nThis week am grateful for:\n\n1. \n2. \n3. \n"),
        ),
    ]
