# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 22:13
from __future__ import unicode_literals

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_journalpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='quarter_template',
            field=colegend.core.fields.MarkdownField(default="# Quarter\nQuarters's focus outcomes:\n\n1. \n2. \n3. \n\nLessons learned: \n\nWins: \n\nThis quarter am grateful for:\n\n1. \n2. \n3. \n"),
        ),
        migrations.AddField(
            model_name='journal',
            name='year_template',
            field=colegend.core.fields.MarkdownField(default="# Year\nYears's focus outcomes:\n\n1. \n2. \n3. \n\nLessons learned: \n\nWins: \n\nThis year am grateful for:\n\n1. \n2. \n3. \n"),
        ),
    ]
