# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 14:31
from __future__ import unicode_literals

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_auto_20161215_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='day_template',
            field=colegend.core.fields.MarkdownField(default='# Morning\nDream notes: \n\nThis morning I am grateful for:\n\n1. \n2. \n3. \n\nMy Legend Purpose: \n\n# Day\n??:00 I woke up.\n\n# Evening\nLessons learned: \n\nWins: \n\nTonight I am grateful for:\n\n1. \n2. \n3. \n'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='month_template',
            field=colegend.core.fields.MarkdownField(default='Lessons learned: \n\nWins: \n\nThis month am grateful for:\n\n1. \n2. \n3. \n'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='quarter_template',
            field=colegend.core.fields.MarkdownField(default='Lessons learned: \n\nWins: \n\nThis quarter am grateful for:\n\n1. \n2. \n3. \n'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='week_template',
            field=colegend.core.fields.MarkdownField(default='Lessons learned: \n\nWins: \n\nThis week am grateful for:\n\n1. \n2. \n3. \n'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='year_template',
            field=colegend.core.fields.MarkdownField(default='Lessons learned: \n\nWins: \n\nThis year am grateful for:\n\n1. \n2. \n3. \n'),
        ),
    ]
