# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 09:36
from __future__ import unicode_literals

import colegend.core.fields
import colegend.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journals', '0009_auto_20170605_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='day', max_length=5, verbose_name='scope')),
                ('start', models.DateField(verbose_name='start')),
                ('content', colegend.core.fields.MarkdownField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='journal_entries', to='tags.Tag')),
            ],
            options={
                'ordering': ['-start'],
                'verbose_name_plural': 'Journal entries',
                'verbose_name': 'Journal Entry',
                'get_latest_by': 'start',
                'default_related_name': 'journal_entries',
            },
            bases=(colegend.core.models.OwnedCheckMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together=set([('owner', 'scope', 'start')]),
        ),
    ]
