# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0011_auto_20170731_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='keywords',
            field=models.CharField(blank=True, help_text='What were the most important experiences/topics on this day?', max_length=500),
        ),
    ]
