# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0013_auto_20170731_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='keywords',
            field=models.CharField(blank=True, help_text='What were the most important experiences/topics?', max_length=500),
        ),
    ]
