# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 23:19
from __future__ import unicode_literals

import colegend.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0014_auto_20170731_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='content',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='keywords',
            field=models.CharField(help_text='What were the most important experiences/topics?', max_length=500),
        ),
    ]
