# Generated by Django 2.0.3 on 2018-04-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0015_auto_20171122_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='streak',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='streak'),
        ),
        migrations.AddField(
            model_name='journal',
            name='streak_max',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='best streak'),
        ),
    ]
