# Generated by Django 2.0.3 on 2018-04-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0016_auto_20180409_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='quarter_template',
        ),
    ]
