# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:09
from __future__ import unicode_literals

import colegend.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='day', max_length=5, verbose_name='scope')),
                ('start', models.DateField(verbose_name='start')),
                ('likes', models.TextField()),
                ('dislikes', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start'],
                'verbose_name_plural': 'Interview entries',
                'get_latest_by': 'start',
                'default_related_name': 'interview_entries',
                'verbose_name': 'Interview Entry',
            },
            bases=(colegend.core.models.OwnedCheckMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='interviewentry',
            unique_together=set([('owner', 'scope', 'start')]),
        ),
    ]
