# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:44
from __future__ import unicode_literals

import annoying.fields
import colegend.core.fields
import colegend.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_status'),
        ('studio', '0003_auto_20170731_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(verbose_name='scope')),
                ('content', colegend.core.fields.MarkdownField()),
            ],
            options={
                'verbose_name_plural': 'Chapters',
                'default_related_name': 'chapters',
                'verbose_name': 'Chapter',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('owner', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='story', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'default_related_name': 'story',
                'verbose_name': 'Story',
            },
            bases=(colegend.core.models.OwnedCheckMixin, models.Model),
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='studio.Story'),
        ),
    ]
