# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_auto_20171111_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='title',
            new_name='name',
        ),
    ]
