# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_auto_20171111_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewentry',
            options={'get_latest_by': 'start', 'ordering': ['-start'], 'verbose_name': 'Interview', 'verbose_name_plural': 'Interviews'},
        ),
    ]
