# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 11:46
from __future__ import unicode_literals

import colegend.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('app', models.CharField(choices=[('home', 'home'), ('arcade', 'arcade'), ('office', 'office'), ('community', 'community'), ('studio', 'studio'), ('academy', 'academy'), ('journey', 'journey')], max_length=10, verbose_name='app')),
                ('level', models.IntegerField(verbose_name='level')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(colegend.core.models.OwnedCheckMixin, models.Model),
        ),
    ]
