# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_auto_20170731_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='level',
        ),
    ]
