# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_auto_20171103_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='action',
            field=models.CharField(choices=[('home', 'home'), ('arcade', 'arcade'), ('office', 'office'), ('community', 'community'), ('studio', 'studio'), ('academy', 'academy'), ('journey', 'journey')], max_length=100, verbose_name='action'),
        ),
    ]
