# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentationindexpage',
            options={'verbose_name': 'Documentation index'},
        ),
        migrations.AlterModelOptions(
            name='documentationpage',
            options={'verbose_name': 'Documentation', 'verbose_name_plural': 'Documentation'},
        ),
    ]
