# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 12:25
from __future__ import unicode_literals

import colegend.core.models
import colegend.core.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.datetime.today,
                                          validators=[colegend.core.validators.validate_date_present_or_past])),
                ('locations', models.CharField(help_text="separated by ';'", max_length=255)),
                ('keywords',
                 models.CharField(blank=True, help_text='What were the most important experiences/topics on this day?',
                                  max_length=255)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayentries',
                                              to='journals.Journal')),
            ],
            options={
                'verbose_name': 'DayEntry',
                'verbose_name_plural': 'Dayentries',
            },
            bases=(colegend.core.models.AutoUrlsMixin, models.Model),
        ),
    ]
