# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 12:59
from __future__ import unicode_literals

import colegend.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dayentries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayentry',
            name='content',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='dayentry',
            name='locations',
            field=models.CharField(help_text="Separated by ';'", max_length=255),
        ),
    ]
