# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dayentries', '0002_auto_20160124_1359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dayentry',
            unique_together=set([('journal', 'date')]),
        ),
    ]
