# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0001_initial'),
        ('dayentries', '0003_auto_20160124_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayentry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
