# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dayentries', '0004_dayentry_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayentry',
            options={'verbose_name': 'Day Entry', 'verbose_name_plural': 'Dayentries'},
        ),
    ]
