# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 16:25
from __future__ import unicode_literals

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dayentries', '0005_auto_20160129_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayentry',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Day Entry',
                     'verbose_name_plural': 'Dayentries'},
        ),
        migrations.AlterField(
            model_name='dayentry',
            name='content',
            field=colegend.core.fields.MarkdownField(),
        ),
    ]
