# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayentries', '0008_auto_20161120_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayentry',
            name='focus',
            field=models.TextField(blank=True),
        ),
    ]
