# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0008_auto_20160602_1833'),
        ('dayentries', '0009_dayentry_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayentry',
            name='outcomes',
            field=models.ManyToManyField(related_name='day_focus', to='outcomes.Outcome'),
        ),
    ]
