# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0008_auto_20160602_1833'),
        ('dayentries', '0010_dayentry_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayentry',
            name='outcome_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outcomes.Outcome'),
        ),
        migrations.AlterField(
            model_name='dayentry',
            name='outcomes',
            field=models.ManyToManyField(related_name='day_focus', to='outcomes.Outcome', verbose_name='Focus outcomes'),
        ),
    ]
