# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 19:21
from __future__ import unicode_literals

from django.db import migrations


def backup_focus(apps, schema_editor):
    DayEntry = apps.get_model("dayentries", "DayEntry")
    for entry in DayEntry.objects.all():
        if entry.content and entry.focus:
            entry.content = "Focus:\n{}\n\n{}".format(entry.focus, entry.content)
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dayentries', '0012_auto_20170208_2017'),
    ]

    operations = [
        migrations.RunPython(backup_focus),
        migrations.RemoveField(
            model_name='dayentry',
            name='focus',
        ),
        migrations.RemoveField(
            model_name='dayentry',
            name='outcomes',
        ),
    ]
