# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 22:00
from __future__ import unicode_literals

from django.db import migrations


def create_focus_from_entries(apps, schema_editor):
    DayEntry = apps.get_model('dayentries', 'DayEntry')
    Focus = apps.get_model('office', 'Focus')
    for entry in DayEntry.objects.all():
        if entry.outcome_1 or entry.outcome_2 or entry.outcome_3 or entry.outcome_4:
            scope = 'day'
            Focus.objects.create(
                owner=entry.journal.owner,
                scope=scope,
                start=entry.date,
                outcome_1=entry.outcome_1,
                outcome_2=entry.outcome_2,
                outcome_3=entry.outcome_3,
                outcome_4=entry.outcome_4,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('dayentries', '0013_auto_20170208_2021'),
        ('office', '0006_auto_20170609_1742'),
    ]

    operations = [
        migrations.RunPython(create_focus_from_entries),
    ]
