# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 01:31
from __future__ import unicode_literals

import colegend.core.fields
import colegend.news.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('date', models.DateTimeField(default=colegend.news.models.get_current_date, verbose_name='start')),
                ('image_url', models.URLField(blank=True, verbose_name='image url')),
                ('description', models.TextField(blank=True, verbose_name='short description')),
                ('content', colegend.core.fields.MarkdownField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'default_related_name': 'news',
                'verbose_name_plural': 'news',
            },
        ),
    ]
