# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 01:44
from __future__ import unicode_literals

import colegend.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=colegend.news.models.get_current_date, verbose_name='date'),
        ),
    ]
