# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='news',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='video url'),
        ),
    ]
