# Generated by Django 2.0.4 on 2018-07-24 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_load_initial_data'),
        ('news', '0006_auto_20180316_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='categories.Category'),
        ),
    ]
