# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:04
from __future__ import unicode_literals

import colegend.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20171130_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
    ]
