# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_auto_20171130_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, verbose_name='author'),
        ),
    ]
