# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20171130_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
