# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_book_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, help_text='Staff notes.', verbose_name='notes'),
        ),
    ]
