# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_book_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'default_related_name': 'tags',
                'ordering': ['name'],
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='academy.BookTag'),
        ),
    ]
