# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_auto_20171212_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='url'),
        ),
    ]
