# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-12 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_waitinglist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaitingList',
            new_name='WaitingListItem',
        ),
    ]
