# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-12 17:36
from __future__ import unicode_literals

import colegend.welcome.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_auto_20170612_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinguser',
            name='code',
            field=models.PositiveSmallIntegerField(default=colegend.welcome.models.generate_code),
        ),
    ]
