# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 09:12
from __future__ import unicode_literals

import colegend.core.utils.media_paths
from django.db import migrations, models
import easy_thumbnails.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160123_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'legend', 'verbose_name_plural': 'legends'},
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=colegend.core.utils.media_paths.UploadToOwnedDirectory('avatars'), verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('N', 'neutral')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='phone'),
        ),
    ]
