# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-31 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160406_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
