# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 21:46
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_registration_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='International format: e.g "+4917612345678"', max_length=128, verbose_name='phone'),
        ),
    ]
