# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20161219_1954'),
        ('users', '0009_auto_20161015_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='duo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='community.Duo', verbose_name='duo'),
        ),
    ]
