# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_duo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='purpose',
            field=models.CharField(default='I am a legend, defining my legend purpose as a member of colegend.', help_text='I am a legend, <what you are doing or being> as <the role you are doing it as>.', max_length=255, verbose_name='legend purpose'),
        ),
    ]
