# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170610_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('N', 'neutral')], default='N', max_length=1, verbose_name='gender'),
        ),
    ]
