# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to=settings.AUTH_USER_MODEL, verbose_name='mentor'),
        ),
    ]
