# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:50
from __future__ import unicode_literals

import colegend.core.utils.media_paths
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=colegend.core.utils.media_paths.UploadToOwnedDirectory('avatars'), verbose_name='avatar'),
        ),
    ]
