# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20171203_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.SmallIntegerField(default=0, help_text='¤', verbose_name='balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Designates whether this user has access to premium content.', verbose_name='premium'),
        ),
    ]
