# Generated by Django 2.0.4 on 2018-04-29 21:56

import colegend.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180322_1600'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', colegend.users.models.UserManager()),
            ],
        ),
    ]
