# Generated by Django 2.0.4 on 2018-07-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180429_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='purpose',
            field=models.CharField(default='I am a legend, defining my legend purpose as a member of coLegend.', help_text='I am a legend, <what you are doing or being> as <the role you are doing it as>.', max_length=255, verbose_name='legend purpose'),
        ),
    ]
