# Generated by Django 2.0.4 on 2018-07-17 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoints', '0002_auto_20160118_2151'),
        ('users', '0023_auto_20180717_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercheckpoint',
            options={'verbose_name': 'User Checkpoint', 'verbose_name_plural': 'User Checkpoints'},
        ),
        migrations.AlterField(
            model_name='usercheckpoint',
            name='checkpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_checkpoints', to='checkpoints.Checkpoint'),
        ),
        migrations.AlterField(
            model_name='usercheckpoint',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_checkpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usercheckpoint',
            unique_together={('owner', 'checkpoint')},
        ),
    ]
