# Generated by Django 2.0.4 on 2018-07-26 11:05

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20180717_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notes',
            field=colegend.core.fields.MarkdownField(blank=True, help_text='Staff notes.', verbose_name='notes'),
        ),
    ]
