# Generated by Django 2.0.4 on 2018-08-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='chat id'),
        ),
    ]
