# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 17:43
from __future__ import unicode_literals

import colegend.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'outcomes',
                'verbose_name': 'outcome',
                'verbose_name_plural': 'outcomes',
            },
            bases=(colegend.core.models.AutoUrlsMixin, colegend.core.models.OwnedCheckMixin, models.Model),
        ),
    ]
