# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 18:50
from __future__ import unicode_literals

import colegend.core.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='date',
            field=models.DateField(blank=True, help_text='When will I start/continue?', null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='deadline'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='inbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outcome',
            name='review',
            field=models.PositiveSmallIntegerField(choices=[(0, 'daily'), (1, 'weekly'), (2, 'monthly'), (3, 'quarterly'), (4, 'yearly'), (5, 'sometime')], default=0, help_text='Minimum review frequency', verbose_name='review'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'open'), (1, 'waiting'), (2, 'closed')], default=0, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='time_estimate',
            field=colegend.core.modelfields.IntuitiveDurationField(blank=True, null=True, verbose_name='time estimate'),
        ),
    ]
