# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0002_auto_20160524_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='review',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'daily'), (1, 'weekly'), (2, 'monthly'), (3, 'quarterly'), (4, 'yearly'), (5, 'sometime')], help_text='Minimum review frequency', null=True, verbose_name='review'),
        ),
    ]
