# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('outcomes', '0006_auto_20160525_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
