# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0007_outcome_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='inbox',
            field=models.BooleanField(default=True),
        ),
    ]
