# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-08 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0008_auto_20160602_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='review',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'daily'), (1, 'weekly'), (2, 'monthly'), (4, 'yearly'), (5, 'sometime')], help_text='Minimum review frequency', null=True, verbose_name='review'),
        ),
    ]
