# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:40
from __future__ import unicode_literals

from django.db import migrations, models


def update_outcome_data(apps, schema_editor):
    Outcome = apps.get_model('outcomes', 'Outcome')
    for outcome in Outcome.objects.all():
        outcome.status_backup = outcome.status
        outcome.save()


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0011_auto_20170617_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='status_backup',
            field=models.PositiveSmallIntegerField(choices=[(1, 'open'), (2, 'waiting'), (3, 'done'), (4, 'canceled')], null=True, verbose_name='status'),
        ),
        migrations.RunPython(update_outcome_data),
    ]
