# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:56
from __future__ import unicode_literals

from django.db import migrations, models


def update_outcome_data(apps, schema_editor):
    Outcome = apps.get_model('outcomes', 'Outcome')
    for outcome in Outcome.objects.all():
        status = outcome.status_backup
        if status == 1:
            outcome.status = 'open'
        elif status == 2:
            outcome.status = 'waiting'
        elif status == 3:
            outcome.status = 'done'
        elif status == 4:
            outcome.status = 'canceled'
        else:
            raise Exception('status {} not found'.format(status))
        outcome.save()


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0012_outcome_status_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('waiting', 'waiting'), ('done', 'done'), ('canceled', 'canceled')], default='open', max_length=10, verbose_name='status'),
        ),
        migrations.RunPython(update_outcome_data),
    ]
