# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0013_auto_20170622_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='status_backup',
        ),
    ]
