# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 22:21
from __future__ import unicode_literals

from django.db import migrations, models


def update_outcome_data(apps, schema_editor):
    Outcome = apps.get_model('outcomes', 'Outcome')
    for outcome in Outcome.objects.all():
        if outcome.status == 'open':
            outcome.status = 'current'
            outcome.save()


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0015_auto_20170731_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='status',
            field=models.CharField(choices=[('future', 'canceled'), ('waiting', 'waiting'), ('current', 'open'), ('done', 'done'), ('canceled', 'canceled')], default='current', max_length=10, verbose_name='status'),
        ),
        migrations.RunPython(update_outcome_data),
    ]
