# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0016_auto_20170831_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='outcomes.Outcome')),
            ],
            options={
                'abstract': False,
                'default_related_name': 'steps',
                'ordering': ('order',),
            },
        ),
    ]
