# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0017_step'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('outcome', 'name')]),
        ),
    ]
