# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0020_auto_20180308_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcome',
            options={'ordering': ['-score', '-modified'], 'verbose_name': 'outcome', 'verbose_name_plural': 'outcomes'},
        ),
    ]
