# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0021_auto_20180309_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcome',
            options={'ordering': ['status', '-score', '-modified'], 'verbose_name': 'outcome', 'verbose_name_plural': 'outcomes'},
        ),
        migrations.AlterField(
            model_name='outcome',
            name='status',
            field=models.CharField(choices=[('current', 'open'), ('waiting', 'waiting'), ('future', 'canceled'), ('done', 'done'), ('canceled', 'canceled')], default='current', max_length=10, verbose_name='status'),
        ),
    ]
