# Generated by Django 2.0.4 on 2018-07-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0023_auto_20180316_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='related_outcomes',
            field=models.ManyToManyField(blank=True, related_name='_outcome_related_outcomes_+', to='outcomes.Outcome'),
        ),
    ]
