# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
    ]
