# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-date'], 'verbose_name': 'donation', 'verbose_name_plural': 'donations'},
        ),
    ]
