# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new clan', max_length=255, verbose_name='name')),
            ],
            options={
                'default_related_name': 'clans',
            },
        ),
        migrations.CreateModel(
            name='CommunityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'community',
                'verbose_name_plural': 'communities',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Duo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new duo', max_length=255, verbose_name='name')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duos', to='community.Clan', verbose_name='clan')),
                ('members', models.ManyToManyField(related_name='duos', to=settings.AUTH_USER_MODEL, verbose_name='members')),
            ],
            options={
                'default_related_name': 'duos',
            },
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new tribe', max_length=255, verbose_name='name')),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tribes', to=settings.AUTH_USER_MODEL, verbose_name='mentor')),
            ],
            options={
                'default_related_name': 'tribes',
            },
        ),
        migrations.AddField(
            model_name='clan',
            name='tribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clans', to='community.Tribe', verbose_name='tribe'),
        ),
    ]
