# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-10 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_clanpage_duopage_mentorpage_tribepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clan',
            name='tribe',
        ),
        migrations.RemoveField(
            model_name='duo',
            name='clan',
        ),
        migrations.RemoveField(
            model_name='tribe',
            name='mentor',
        ),
    ]
