# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20170610_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='duo',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='tribe',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
    ]
