# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-08 22:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20170609_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
