# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0009_auto_20170609_0027'),
        ('office', '0004_auto_20170609_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focus',
            name='outcomes',
        ),
        migrations.AddField(
            model_name='focus',
            name='outcome_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_1', to='outcomes.Outcome'),
        ),
        migrations.AddField(
            model_name='focus',
            name='outcome_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_2', to='outcomes.Outcome'),
        ),
        migrations.AddField(
            model_name='focus',
            name='outcome_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_3', to='outcomes.Outcome'),
        ),
        migrations.AddField(
            model_name='focus',
            name='outcome_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_4', to='outcomes.Outcome'),
        ),
    ]
