# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_auto_20170609_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='scope',
            field=models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='day', max_length=5, verbose_name='scope'),
        ),
    ]
