# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_auto_20170609_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='focus',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
