# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20170623_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='start',
            field=models.DateField(verbose_name='start'),
        ),
    ]
