# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


def update_data(apps, schema_editor):
    Focus = apps.get_model('office', 'Focus')
    for focus in Focus.objects.all():
        focus.save()


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_auto_20170628_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='end',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='end'),
            preserve_default=False,
        ),
        migrations.RunPython(update_data),
    ]
