# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_auto_20170731_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focus',
            options={'ordering': ['start'], 'verbose_name': 'Focus', 'verbose_name_plural': 'Focuses'},
        ),
    ]
