# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 22:34
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone


def create_focus_from_entries(apps, schema_editor):
    YearEntry = apps.get_model('yearentries', 'YearEntry')
    Focus = apps.get_model('office', 'Focus')
    for entry in YearEntry.objects.all():
        if entry.outcome_1 or entry.outcome_2 or entry.outcome_3 or entry.outcome_4:
            scope = 'year'
            # Using date conversion explicitly
            # otherwise I get an error `AttributeError: 'YearEntry' object has no attribute 'date'`.
            date = timezone.datetime.strptime('{}'.format(entry.year), "%Y").date()
            Focus.objects.create(
                owner=entry.journal.owner,
                scope=scope,
                start=date,
                outcome_1=entry.outcome_1,
                outcome_2=entry.outcome_2,
                outcome_3=entry.outcome_3,
                outcome_4=entry.outcome_4,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('yearentries', '0003_auto_20170213_1641'),
        ('office', '0006_auto_20170609_1742'),
    ]

    operations = [
        migrations.RunPython(create_focus_from_entries),
    ]
