# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('roles', '0002_auto_20160119_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='item',
            field=models.CharField(blank=True, max_length=255, verbose_name='item'),
        ),
    ]
