# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_create_initial_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
    ]
