# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-19 20:46
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_auto_20160406_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='icon',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='roles/icons/'),
        ),
    ]
