# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0006_role_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='metrics',
            field=models.TextField(blank=True),
        ),
    ]
