# Generated by Django 2.0.4 on 2018-06-22 23:00

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_auto_20180622_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='notes',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='notes'),
        ),
    ]
