# Generated by Django 2.0.4 on 2018-06-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0009_auto_20180623_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='circle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='roles.Circle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('circle', 'name')},
        ),
    ]
