# Generated by Django 2.0.4 on 2018-06-28 13:05

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0010_auto_20180623_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='accountabilities',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='accountabilities'),
        ),
        migrations.AddField(
            model_name='role',
            name='checklists',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='checklists'),
        ),
        migrations.AddField(
            model_name='role',
            name='domains',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='domains'),
        ),
        migrations.AddField(
            model_name='role',
            name='history',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='history'),
        ),
        migrations.AddField(
            model_name='role',
            name='notes',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='role',
            name='policies',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='policies'),
        ),
        migrations.AddField(
            model_name='role',
            name='purpose',
            field=colegend.core.fields.MarkdownField(default='', verbose_name='purpose'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='strategy',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='strategy'),
        ),
        migrations.AlterField(
            model_name='role',
            name='metrics',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='metrics'),
        ),
    ]
