# Generated by Django 2.0.4 on 2018-06-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0011_auto_20180628_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_circle',
            field=models.BooleanField(default=False, help_text='Designates whether this role is a collection of sub-roles.', verbose_name='circle'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_core',
            field=models.BooleanField(default=False, help_text='Designates whether this role is a core roles.', verbose_name='core'),
        ),
        migrations.AddField(
            model_name='role',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'is_circle': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='roles.Role'),
        ),
    ]
