# Generated by Django 2.0.4 on 2018-06-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0013_auto_20180628_1621'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('parent', 'name')},
        ),
        migrations.RemoveField(
            model_name='role',
            name='circle',
        ),
    ]
