# Generated by Django 2.0.4 on 2018-06-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0014_auto_20180628_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='parent',
            new_name='circle',
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('circle', 'name')},
        ),
    ]
