# Generated by Django 2.0.4 on 2018-06-29 08:58

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0017_auto_20180629_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Circle',
        ),
        migrations.AlterField(
            model_name='role',
            name='powers',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='powers'),
        ),
        migrations.AlterField(
            model_name='role',
            name='services',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='services'),
        ),
    ]
