# Generated by Django 2.0.4 on 2018-07-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0018_auto_20180629_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
    ]
