# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160625_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='This date may be displayed on the blog post. It is not used to schedule posts to go live at a later date.', verbose_name='Display date'),
        ),
    ]
