# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160624_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticlepage',
            name='lead',
            field=models.TextField(blank=True, verbose_name='Lead text'),
        ),
    ]
