# Generated by Django 2.0.4 on 2018-07-24 14:37

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='history',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='history'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='notes'),
        ),
    ]
