# Generated by Django 2.0.4 on 2018-07-24 22:17

import colegend.crm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180724_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(default=colegend.crm.models.get_default_status, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.Status'),
        ),
    ]
