# Generated by Django 2.0.4 on 2018-07-28 10:44

from django.db import migrations, models
import phonenumber_field.modelfields


def convert_blanks_to_nulls(apps, schema_editor):
    Lead = apps.get_model("crm", "Lead")
    for lead in Lead.objects.all():
        save = False
        if not lead.email:
            lead.email = None
            save = True
        if not lead.url:
            lead.url = None
            save = True
        if save:
            lead.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180725_0017'),
    ]

    operations = [
        # Name is not unique anoymore.
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),

        # Allow email, phone and url to be Null.
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='url'),
        ),

        # Convert bank entries for email, phone and url to null to prepare for uniqueness shift.
        migrations.RunPython(convert_blanks_to_nulls),

        # Require email, phone and url to be unique.
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True, unique=True, verbose_name='url'),
        ),
    ]
