# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 00:17
from __future__ import unicode_literals

import colegend.core.fields
import colegend.scopes.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('scope', colegend.scopes.models.ScopeField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='day', max_length=5, verbose_name='scope')),
                ('public', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, verbose_name='image url')),
                ('content', colegend.core.fields.MarkdownField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Staff notes.', verbose_name='notes')),
            ],
            options={
                'default_related_name': 'adventures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdventureTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'default_related_name': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='adventure',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='adventures', to='arcade.AdventureTag'),
        ),
    ]
