# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 15:51
from __future__ import unicode_literals

import colegend.core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0002_auto_20171211_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content', colegend.core.fields.MarkdownField(blank=True)),
                ('image_url', models.URLField(blank=True, verbose_name='image url')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcade.Adventure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adventure',
            name='reviews',
            field=models.ManyToManyField(related_name='adventures', through='arcade.AdventureReview', to=settings.AUTH_USER_MODEL),
        ),
    ]
