# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0003_auto_20171212_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurereview',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_reviews', to='arcade.Adventure'),
        ),
        migrations.AlterField(
            model_name='adventurereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
