# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0005_adventurereview_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventurereview',
            old_name='user',
            new_name='owner',
        ),
    ]
