# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0006_auto_20171212_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventure',
            old_name='reviews',
            new_name='adventurers',
        ),
    ]
