# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0007_auto_20171212_1758'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adventurereview',
            unique_together=set([('owner', 'adventure')]),
        ),
    ]
