# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0008_auto_20171213_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='level'),
        ),
    ]
