# Generated by Django 2.0.3 on 2018-03-22 06:38

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0010_auto_20171217_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='images',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='arcade/adventures/'),
        ),
    ]
