# Generated by Django 2.0.3 on 2018-03-22 08:13

import colegend.core.utils.media_paths
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0012_auto_20180322_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='images',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=colegend.core.utils.media_paths.UploadToAppModelDirectory()),
        ),
    ]
