# Generated by Django 2.0.3 on 2018-03-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0013_auto_20180322_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventure',
            old_name='images',
            new_name='image',
        ),
    ]
