# Generated by Django 2.0.4 on 2018-06-08 21:42

import colegend.core.fields
import colegend.core.utils.media_paths
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0014_auto_20180322_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=colegend.core.utils.media_paths.UploadToAppModelDirectory())),
                ('content', colegend.core.fields.MarkdownField(blank=True)),
                ('notes', colegend.core.fields.MarkdownField(blank=True, help_text='Staff notes.', verbose_name='notes')),
            ],
            options={
                'default_related_name': 'cards',
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=colegend.core.utils.media_paths.UploadToAppModelDirectory())),
                ('content', colegend.core.fields.MarkdownField(blank=True)),
                ('notes', colegend.core.fields.MarkdownField(blank=True, help_text='Staff notes.', verbose_name='notes')),
            ],
            options={
                'default_related_name': 'decks',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='arcade.Deck'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('deck', 'name')},
        ),
    ]
