# Generated by Django 2.0.4 on 2018-06-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_load_initial_data'),
        ('arcade', '0015_auto_20180608_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='card',
            name='categories',
            field=models.ManyToManyField(related_name='cards', to='categories.Category', verbose_name='categories'),
        ),
    ]
