# Generated by Django 2.0.4 on 2018-06-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0016_auto_20180609_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='cards', to='categories.Category', verbose_name='categories'),
        ),
    ]
