# Generated by Django 2.0.4 on 2018-06-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0017_auto_20180613_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
