# Generated by Django 2.0.4 on 2018-07-02 12:35

import colegend.core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0018_card_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='What is the quote about?', max_length=255, unique=True, verbose_name='name')),
                ('content', colegend.core.fields.MarkdownField(blank=True)),
                ('accepted', models.BooleanField(default=False, verbose_name='accepted')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jokes', to=settings.AUTH_USER_MODEL, verbose_name='provider')),
            ],
            options={
                'default_related_name': 'jokes',
            },
        ),
    ]
