# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20171115_2254'),
        ('cards', '0003_create_initial_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='category',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
