# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 21:56
from __future__ import unicode_literals

import colegend.core.fields
import colegend.core.models
import colegend.journals.quarterentries.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0007_journalpage'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(default=colegend.journals.quarterentries.utils.get_current_year, validators=[django.core.validators.MaxValueValidator(4000)])),
                ('quarter', models.PositiveIntegerField(default=colegend.journals.quarterentries.utils.get_current_quarter, validators=[django.core.validators.MaxValueValidator(4)])),
                ('keywords', models.CharField(blank=True, help_text='What were the most important experiences/topics this quarter?', max_length=255)),
                ('content', colegend.core.fields.MarkdownField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterentries', to='journals.Journal')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
            options={
                'verbose_name_plural': 'Quarterentries',
                'verbose_name': 'Quarter Entry',
                'ordering': ['-year', '-quarter'],
            },
            bases=(colegend.core.models.AutoUrlsMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='quarterentry',
            unique_together=set([('journal', 'year', 'quarter')]),
        ),
    ]
