# Generated by Django 2.0.3 on 2018-03-16 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_auto_20170731_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiderelation',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidee_relations', to=settings.AUTH_USER_MODEL),
        ),
    ]
