# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 08:24
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='owner',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hero', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
