# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0003_auto_20170910_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hero',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
