# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 22:31
from __future__ import unicode_literals

import annoying.fields
import colegend.core.fields
import colegend.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170810_1727'),
        ('journey', '0004_auto_20170911_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demon',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='demon', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('content', colegend.core.fields.MarkdownField()),
            ],
            options={
                'verbose_name': 'Demon',
                'default_related_name': 'demon',
                'verbose_name_plural': 'Demons',
            },
            bases=(colegend.core.models.OwnedCheckMixin, models.Model),
        ),
    ]
