# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 20:41
from __future__ import unicode_literals

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_demon'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='fears',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='achievements',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='experiments',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='goals',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='habits',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='people',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='powers',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='principles',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='projects',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='questions',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='skills',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='values',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='wishes',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
    ]
