# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 20:47
from __future__ import unicode_literals

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0007_auto_20180127_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='resources',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
    ]
