# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0010_demon_tensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='avatar',
            field=models.URLField(blank=True, max_length=1000, verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='demon',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='hero',
            name='avatar',
            field=models.URLField(blank=True, max_length=1000, verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='hero',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
    ]
