# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 14:25
from __future__ import unicode_literals

import colegend.core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_load_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journey', '0012_hero_routines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='What is the quote about?', max_length=255, unique=True, verbose_name='name')),
                ('content', colegend.core.fields.MarkdownField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='author')),
                ('accepted', models.BooleanField(default=False, verbose_name='accepted')),
                ('used_as_daily', models.DateField(blank=True, null=True, unique=True)),
                ('category', models.ManyToManyField(related_name='quotes', to='categories.Category', verbose_name='category')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL, verbose_name='provider')),
            ],
            options={
                'default_related_name': 'quotes',
            },
        ),
    ]
