# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0013_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='category',
            new_name='categories',
        ),
    ]
