# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0014_auto_20180310_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='categories',
            field=models.ManyToManyField(related_name='quotes', to='categories.Category', verbose_name='categories'),
        ),
    ]
