# Generated by Django 2.0.3 on 2018-03-25 22:44

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0015_auto_20180310_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='inspirations',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
    ]
