# Generated by Django 2.0.3 on 2018-03-25 23:24

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0016_hero_inspirations'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='mission',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
    ]
