# Generated by Django 2.0.3 on 2018-03-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0017_hero_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='year_topic',
            field=models.CharField(blank=True, max_length=255, verbose_name='year topic'),
        ),
    ]
