# Generated by Django 2.0.3 on 2018-04-04 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journey', '0019_auto_20180330_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='disliked_by',
            field=models.ManyToManyField(related_name='disliked_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
