# Generated by Django 2.0.3 on 2018-04-18 13:16

import colegend.core.fields
import colegend.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journey', '0021_auto_20180405_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('video_url', models.URLField(blank=True, max_length=1000, verbose_name='video url')),
                ('content', colegend.core.fields.MarkdownField(verbose_name='content')),
            ],
            options={
                'default_related_name': 'quests',
            },
        ),
        migrations.CreateModel(
            name='QuestObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(max_length=255, verbose_name='name')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='journey.Quest')),
            ],
            options={
                'default_related_name': 'objectives',
            },
        ),
        migrations.CreateModel(
            name='UserQuestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('completed_objectives', models.ManyToManyField(related_name='quest_statuses', to='journey.QuestObjective')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_statuses', to=settings.AUTH_USER_MODEL)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_statuses', to='journey.Quest')),
            ],
            options={
                'default_related_name': 'quest_statuses',
            },
            bases=(colegend.core.models.OwnedCheckMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='userqueststatus',
            unique_together={('owner', 'quest')},
        ),
    ]
