# Generated by Django 2.0.3 on 2018-04-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0022_auto_20180418_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='questobjective',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='userqueststatus',
            options={'verbose_name': 'Quest status', 'verbose_name_plural': 'Quest statuses'},
        ),
        migrations.AlterField(
            model_name='questobjective',
            name='code',
            field=models.CharField(max_length=255, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='userqueststatus',
            name='completed_objectives',
            field=models.ManyToManyField(blank=True, related_name='quest_statuses', to='journey.QuestObjective'),
        ),
    ]
