# Generated by Django 2.0.4 on 2018-06-22 14:55

import colegend.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0023_auto_20180418_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='topics',
            field=colegend.core.fields.MarkdownField(blank=True),
        ),
    ]
