# Generated by Django 2.0.4 on 2018-07-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0025_auto_20180713_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userqueststatus',
            options={'ordering': ['quest'], 'verbose_name': 'Quest status', 'verbose_name_plural': 'Quest statuses'},
        ),
    ]
