# Generated by Django 2.0.4 on 2018-07-25 14:37

import colegend.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0026_auto_20180720_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='questobjective',
            name='content',
            field=colegend.core.fields.MarkdownField(blank=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='userqueststatus',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
    ]
