# Generated by Django 2.0.4 on 2018-07-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0027_auto_20180725_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
