# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 18:11
from __future__ import unicode_literals

import colegend.core.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20161127_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('image_url', models.URLField(blank=True, verbose_name='image url')),
                ('content', colegend.core.fields.MarkdownField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
