# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start']},
        ),
    ]
