# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 01:33
from __future__ import unicode_literals

import colegend.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20171105_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=colegend.events.models.get_current_date, verbose_name='start'),
        ),
    ]
