# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpage',
            options={'verbose_name': 'Support'},
        ),
    ]
