# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20160626_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpage',
            options={'verbose_name': 'Content'},
        ),
    ]
