# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 14:31
from __future__ import unicode_literals

import colegend.cms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('cms', '0004_auto_20161127_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Root',
            },
            bases=(colegend.cms.models.UniquePageMixin, 'wagtailcore.page'),
        ),
    ]
