# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-04 13:39
from __future__ import unicode_literals

import colegend.core.fields
import colegend.core.models
import colegend.core.utils.media_paths
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.PositiveSmallIntegerField(choices=[(1, 'day'), (2, 'week'), (3, 'month'), (4, 'quarter'), (5, 'year')], default=1, verbose_name='scope')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=colegend.core.utils.media_paths.UploadToOwnedDirectory('vision'), verbose_name='avatar')),
                ('content', colegend.core.fields.MarkdownField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'visions',
                'default_related_name': 'visions',
                'verbose_name': 'vision',
            },
            bases=(colegend.core.models.AutoUrlsMixin, colegend.core.models.OwnedCheckMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='vision',
            unique_together=set([('owner', 'scope')]),
        ),
    ]
