# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-04 16:34
from __future__ import unicode_literals

import colegend.core.utils.media_paths
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=colegend.core.utils.media_paths.UploadToOwnedDirectory('vision'), verbose_name='image'),
        ),
    ]
