# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visions', '0002_auto_20160604_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='scope',
            field=models.PositiveSmallIntegerField(choices=[(1, 'day'), (2, 'week'), (3, 'month'), (4, 'quarter'), (5, 'year'), (6, 'someday')], default=1, verbose_name='scope'),
        ),
    ]
