# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visions', '0003_auto_20161228_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vision',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
