# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20160109_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='game',
            name='hand',
        ),
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
