# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20160703_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_text',
            field=models.TextField(blank=True),
        ),
    ]
