# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('about', '0004_aboutpage_intro_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
